### ISSUE TITLE
worker fails at every first new job after restart

### ISSUE THREAD

**Issue by necrygor** [postalhq/postal#1146]
Hello,

I'm running postal 1.0.0-67d0f6514d-stable on Debian Stretch.

User sends mail via third party software of their own. Postal receieves and queues mails but right before sending worker.1 stops due to mysql error.

````
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM] ActiveRecord::StatementInvalid: Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused"): SELECT COUNT(*) FROM `servers` WHERE (send_limit_approaching_at IS NOT NULL AND send_limit_approaching_at > '2020-06-01 06:11:20.180075') AND (send_limit_approaching_notified_at IS NULL OR send_limit_approaching_notified_at < '2020-06-01 05:14:20.180480')
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation/calculations.rb:248:in `execute_simple_calculation'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation/calculations.rb:207:in `perform_calculation'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation/calculations.rb:121:in `calculate'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation/calculations.rb:40:in `count'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:285:in `empty?'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/app/app/models/server.rb:305:in `block in send_send_limit_notifications'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/app/app/models/server.rb:302:in `each'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/app/app/models/server.rb:302:in `each_with_object'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/app/app/models/server.rb:302:in `send_send_limit_notifications'
[worker.1:1010] [2020-06-01T09:14:20.182] WARN -- : [ANMLEANDTM]    /opt/postal/app/app/jobs/send_notifications_job.rb:3:in `perform'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/app/lib/postal/worker.rb:55:in `receive_job'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/app/lib/postal/worker.rb:88:in `block in join_queue'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer.rb:56:in `call'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/channel.rb:1703:in `block in handle_frameset'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:97:in `block (2 levels) in run_loop'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `loop'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `block in run_loop'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `catch'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [ANMLEANDTM]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `run_loop'
[worker.1:1010] [2020-06-01T09:14:20.183] INFO -- : [ANMLEANDTM] Finished processing SendNotificationsJob job in 0.003725947s
[worker.1:1010] [2020-06-01T09:14:20.179] WARN -- : [IBUIM00WVQ] ActiveRecord::StatementInvalid: Mysql2::Error: Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused"): SELECT `webhook_requests`.* FROM `webhook_requests` WHERE (retry_after < '2020-06-01 06:14:20.178415')
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `block in execute'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:589:in `block in log'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.0.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_adapter.rb:583:in `log'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:218:in `execute'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:31:in `execute'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:225:in `execute_and_free'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:36:in `exec_query'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:373:in `select'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/database_statements.rb:41:in `select_all'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/abstract/query_cache.rb:95:in `select_all'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/connection_adapters/mysql/database_statements.rb:10:in `select_all'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/querying.rb:39:in `find_by_sql'
[worker.1:1010] [2020-06-01T09:14:20.183] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:702:in `exec_queries'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:583:in `load'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation.rb:260:in `records'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.0.2/lib/active_record/relation/delegation.rb:38:in `each'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/app/app/models/webhook_request.rb:46:in `requeue_all'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/app/app/jobs/requeue_webhooks_job.rb:3:in `perform'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/app/lib/postal/worker.rb:55:in `receive_job'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/app/lib/postal/worker.rb:88:in `block in join_queue'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer.rb:56:in `call'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/channel.rb:1703:in `block in handle_frameset'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:97:in `block (2 levels) in run_loop'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `loop'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `block in run_loop'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `catch'
[worker.1:1010] [2020-06-01T09:14:20.184] WARN -- : [IBUIM00WVQ]    /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `run_loop'
[worker.1:1010] [2020-06-01T09:14:20.184] INFO -- : [IBUIM00WVQ] Finished processing RequeueWebhooksJob job in 0.006376871s
[worker.1:3494] [2020-06-01T09:14:29.698] INFO -- : Worker running with 4 threads
[worker.1:3494] [2020-06-01T09:14:29.704] INFO -- : Joined main queue
````

For connection refused error from mysql, there is nothing wrong with mysql or used credentials. Even so, postal restart seems to fix the situation. I am  unable to pinpoint the problem. For now I plan to check for postal status every now and then and restart if worker fails.

Any help would be appreciated to diagnose.

Thanks.

**Comment by willpower232** [comment]
Does your server have enough memory to keep MySQL running? It may be that it crashes and is unavailable from time to time.

**Comment by necrygor** [comment]
Thank you for your answer. It seems that there is enough RAM for it but I didn't check for temporary downtimes of mysql though. I will test it as soon as possible while monitoring both mysql and postal. 

But I think there is not much to it though. Thanks for help, issue can be closed I think. I will try to write outcome of my test here too.
