### ISSUE TITLE
Issues with some devices that are using Postal - HP printers

### ISSUE THREAD

**Issue by nenominal** [postalhq/postal#1245]
Hi,

I have some issues with some HP printers that are configured to use the postal server.

`502 Invalid/unsupported command`

I followed recommendations of @willpower232  from #556 and I enabled logging for smtp server.

```
[smtp.1:2356] [2020-10-28T19:23:09.545] DEBUG -- : [CCDURI] <= ZTQ5ZjM5
[smtp.1:2356] [2020-10-28T19:23:09.546] DEBUG -- : [CCDURI] => 502 Invalid/unsupported command
[smtp.1:2356] [2020-10-28T19:23:09.546] DEBUG -- : [CCDURI]    Connection closed
[smtp.1:2356] [2020-10-28T19:29:39.696] DEBUG -- : [GWY3NT]    Connection opened from ::ffff:x.x.x.x
[smtp.1:2356] [2020-10-28T19:29:39.698] DEBUG -- : [GWY3NT]    Client identified as ::ffff:x.x.x.y
[smtp.1:2356] [2020-10-28T19:29:39.699] DEBUG -- : [GWY3NT] <= HELO medea
[smtp.1:2356] [2020-10-28T19:29:39.703] DEBUG -- : [GWY3NT] => 250 postal.xxx.xx
[smtp.1:2356] [2020-10-28T19:29:39.703] DEBUG -- : [GWY3NT] <= QUIT
[smtp.1:2356] [2020-10-28T19:29:39.704] DEBUG -- : [GWY3NT] => 221 Closing Connection
[smtp.1:2356] [2020-10-28T19:29:39.705] DEBUG -- : [GWY3NT]    Connection closed
[smtp.1:7516] [2020-10-28T19:29:57.899] INFO -- : Listening on port 25
[smtp.1:7516] [2020-10-28T19:29:59.986] DEBUG -- : [VLR0LE]    Connection opened from ::ffff:x.x.x.x
[smtp.1:7516] [2020-10-28T19:29:59.987] DEBUG -- : [VLR0LE]    Client identified as ::ffff:x.x.x.x
[smtp.1:7516] [2020-10-28T19:29:59.990] DEBUG -- : [VLR0LE] <= EHLO printerhp
[smtp.1:7516] [2020-10-28T19:29:59.993] DEBUG -- : [VLR0LE] => 250-My capabilities are
[smtp.1:7516] [2020-10-28T19:29:59.994] DEBUG -- : [VLR0LE] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:7516] [2020-10-28T19:29:59.996] DEBUG -- : [VLR0LE] <= AUTH CRAM-MD5
[smtp.1:7516] [2020-10-28T19:29:59.997] DEBUG -- : [VLR0LE] => 334 PGNkZDA1ZWUwYmIwYjNlN2Q1NDFiQHBvc3RhbC5jb
[smtp.1:7516] [2020-10-28T19:29:59.998] DEBUG -- : [VLR0LE] <= cG9zdGFsLWludGVybi9wb3N0YWwtY29tdGVjLXJvIGYzYzk5MTVmZGVmY2ViMjFlOW
[smtp.1:7516] [2020-10-28T19:30:00.290] DEBUG -- : [VLR0LE] => 535 Denied
[smtp.1:7516] [2020-10-28T19:30:00.291] DEBUG -- : [VLR0LE] <= ZjI5MTcy
[smtp.1:7516] [2020-10-28T19:30:00.292] DEBUG -- : [VLR0LE] Invalid/unsupported command was: ZjI5MTcy
[smtp.1:7516] [2020-10-28T19:30:00.293] ERROR -- : [VLR0LE] An error occurred while processing data from a client.
[smtp.1:7516] [2020-10-28T19:30:00.294] ERROR -- : [VLR0LE] NoMethodError: undefined method `strip' for true:TrueClass
[smtp.1:7516] [2020-10-28T19:30:00.295] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:165:in `block (3 levels) in run_event_loop'
[smtp.1:7516] [2020-10-28T19:30:00.295] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:164:in `each'
[smtp.1:7516] [2020-10-28T19:30:00.296] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:164:in `block (2 levels) in run_event_loop'
[smtp.1:7516] [2020-10-28T19:30:00.297] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `select'
[smtp.1:7516] [2020-10-28T19:30:00.298] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `block in run_event_loop'
[smtp.1:7516] [2020-10-28T19:30:00.298] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `loop'
[smtp.1:7516] [2020-10-28T19:30:00.299] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `run_event_loop'
[smtp.1:7516] [2020-10-28T19:30:00.300] ERROR -- : [VLR0LE] /opt/postal/app/lib/postal/smtp_server/server.rb:260:in `run'
[smtp.1:7516] [2020-10-28T19:30:00.300] ERROR -- : [VLR0LE] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[smtp.1:7516] [2020-10-28T19:30:00.301] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `block in execute'
[smtp.1:7516] [2020-10-28T19:30:00.302] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `each'
[smtp.1:7516] [2020-10-28T19:30:00.303] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:273:in `execute'
[smtp.1:7516] [2020-10-28T19:30:00.304] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
[smtp.1:7516] [2020-10-28T19:30:00.304] ERROR -- : [VLR0LE] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:7516] [2020-10-28T19:30:00.305] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:194:in `invoke_with_call_chain'
[smtp.1:7516] [2020-10-28T19:30:00.306] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/task.rb:183:in `invoke'
[smtp.1:7516] [2020-10-28T19:30:00.306] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:160:in `invoke_task'
[smtp.1:7516] [2020-10-28T19:30:00.307] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block (2 levels) in top_level'
[smtp.1:7516] [2020-10-28T19:30:00.308] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `each'
[smtp.1:7516] [2020-10-28T19:30:00.308] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:116:in `block in top_level'
[smtp.1:7516] [2020-10-28T19:30:00.309] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:125:in `run_with_threads'
[smtp.1:7516] [2020-10-28T19:30:00.310] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:110:in `top_level'
[smtp.1:7516] [2020-10-28T19:30:00.311] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:83:in `block in run'
[smtp.1:7516] [2020-10-28T19:30:00.311] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:186:in `standard_exception_handling'
[smtp.1:7516] [2020-10-28T19:30:00.312] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/lib/rake/application.rb:80:in `run'
[smtp.1:7516] [2020-10-28T19:30:00.313] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
[smtp.1:7516] [2020-10-28T19:30:00.313] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:7516] [2020-10-28T19:30:00.314] ERROR -- : [VLR0LE] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```
Any ideas? 

Thanks.

**Comment by willpower232** [comment]
> 535 Denied

Suggests that your combination of from address and credential aren't correct. It may be that the printer struggles to accept that so I'd suggest generating new details and double checking.

Also the credential you were using is easily decipherable from the log entries above so you should change them fully if you can.

**Comment by nenominal** [comment]
I've tested many times, I'm very sure that the authentication details are OK, because on other devices it works.
On the other hand, this printers are working great with Gmail, the authentication has no problem there.

`Also the credential you were using is easily decipherable from the log entries above so you should change them fully if you can.`
Yeah, well, I have't think it through it seems, lucky me it's just a test account, thanks for pointing it out.

**Comment by willpower232** [comment]
I seem to vaguely remember some printers having trouble with passwords over a certain length which might explain why it was denied, you could double check the form in the printer UI to see if it mentions any lengths and use the database directly to shorten the password for the credential.

**Comment by nenominal** [comment]
That's an idea, I'll check it out, thanks!
