### ISSUE TITLE
Feature: Ubuntu 20.04 LTS support

### ISSUE THREAD

**Issue by Lyamc** [postalhq/postal#1265]
I've taken the 16.04 Ubuntu bash script and modified it heavily. This bash script that I've tested thouroughly on my machine. However, I'm new to this whole thing (my smtp server still doesn't work) so don't take my word for it!

In the future I might suggest breaking this one script into several parts so that only a single part needs to be re-run, such as openssl config.

The script can be run multiple times to install again and again and again.

It automagically generates a password for the user postal which is used for openssl, local login and DB login.

The information entered in OpenSSL configuration is used throughout the application: **automatically updating the postal config with the proper hostnames.**

```
#!/bin/bash


#
# Assigning Variables
#

# Postal specific variables for configuration
scriptname=$(basename "$0")
postaluser="postal"
postaldir="/opt/postal"
ssldir="/opt/postal/ssl"
sslbin="openssl"
postalpass="$ssldir/password.bak"
passgen=$($sslbin rand -hex 20)
nginxdir="/etc/nginx"
nginxwww="/var/www/html"
TIMEDATE=$(date +%Y-%m-%d_%R:%S)


# Load SSL Defaults
sslcountry="US"
sslstate="New York"
sslcity="New York"
sslorganization="Company Ltd."
sslorgunit="Admin"
sslemail="admin@example.com"
dnsname1="example.com"
dnsname2="www.example.com"
fqdnhostname="$dnsname2"

# Kill program upon error
set -e


# Get dependencies
function postal.depend
{
	sudo apt update
	sudo apt install -y software-properties-common ruby ruby-dev build-essential libssl-dev mariadb-server libmysqlclient-dev rabbitmq-server nodejs git nginx wget nano
	echo "Apt install complete."
	echo ""
	postalpass="$ssldir/password.bak"
	passgen=$($sslbin rand -hex 20)
	rubybin=$(gem env | grep "RUBY EXECUTABLE" | cut -d ":" -f2 | cut -d " " -f2)
	sudo setcap 'cap_net_bind_service=+ep' $rubybin
	echo "Setcapped $rubybin"
	echo "Installing bundler and procodile..."
	sudo gem install bundler procodile
	echo "Gem install complete."
	echo ""
}

function postal.showpassword
{
	sudo cat "$postalpass"
}

# Generate or update postal password
function postal.password 
{
	if test -f "$postalpass"
		then
    			echo "SSL Postal key found at $ssldir."
    			sudo chmod 700 "$postalpass"
    			passgen=$(postal.showpassword)
		else
			echo "No postalkey found at $ssldir. Creating..."
			postal.checkdir
			sudo touch "$postalpass"
			sudo chown $USER:$USER "$postalpass"
			echo $passgen > "$postalpass"
			sudo chmod 700 "$postalpass"
			sudo chown root:root "$postalpass"
	fi
}


function postal.checkuser
{
	echo "Checking postal user."
	if id "$postaluser" &>/dev/null
		then
    			echo 'User $postaluser already exists.'
    			echo "Updating password for $postaluser"
    			sudo usermod postal -aG sudo -m -d $postaldir -s /bin/bash 
    			sudo chown $postaluser:$postaluser -R $postaldir
			echo -e "$passgen\n$passgen" | sudo passwd $postaluser
    			
		else
    			echo 'User $postaluser not found, creating...'
    			sudo useradd -r -m -d $postaldir -s /bin/bash postal
    			echo -e "$passgen\n$passgen" | sudo passwd $postaluser
	fi
}

# Check postal directory
function postal.checkdir 
{
	if test -f "$postaldir"
		then
    			echo "Postal directory found at $postaldir."
    			postal.checkuser
		else
  			echo "No Postal directory found at $postaldir. Creating..."
  			postal.checkuser
	fi
	
	echo "Checking $ssldir"
	if test -f "$ssldir"
		then
			:
		else
			sudo mkdir -p $ssldir		
	fi
}




#
# SSL Configuration
#
# Prepare config file for reading/editing

function postal.readssl
{
	if test -f "$ssldir/ssl.cnf"
		then
 	   		echo "SSL configuration found at $ssldir/ssl.cnf."
 	   		sudo chown $USER:$USER $ssldir/ssl.cnf
 	   		sudo chmod 700 $ssldir/ssl.cnf
    	
# Grab variables from config
			sslcountry=$(grep "C = " $ssldir/ssl.cnf | sed 's/C = //g')
			sslstate=$(grep "ST = " $ssldir/ssl.cnf | sed 's/ST = //g')
			sslcity=$(grep "L = " $ssldir/ssl.cnf | sed 's/L = //g')
			sslorganization=$(grep "O = " $ssldir/ssl.cnf | sed 's/O = //g')
			sslorgunit=$(grep "OU = " $ssldir/ssl.cnf | sed 's/OU = //g')
			fqdnhostname=$(grep "CN = " $ssldir/ssl.cnf | sed 's/CN = //g')
			sslemail=$(grep "emailAddress = " $ssldir/ssl.cnf | sed 's/emailAddress = //g')
			dnsname1=$(grep "DNS.1 = " $ssldir/ssl.cnf | sed 's/DNS.1 = //g')
			dnsname2=$(grep "DNS.2 = " $ssldir/ssl.cnf | sed 's/DNS.2 = //g')
			echo "SSL Configuration Imported"
			sudo chown root:root "$ssldir/ssl.cnf"
			sudo cp "$ssldir/ssl.cnf" "$ssldir/ssl_$TIMEDATE.bak"
			

		else
 	 		sudo touch "$ssldir/ssl.cnf"
	fi

}


function postal.modifyssl
{

# Begins loop for configuration

	response=no
	while [[ $response =~ ^(N|n|No|no|NO)$ ]];
		do
  			response=yes
  			clear
  			sleep 0.1s
  			echo "---------------------------------------------------------"
  			echo "SSL Configuration"
  			echo "---------------------------------------------------------"
  			echo -e "        Country: $sslcountry"
  			echo -e "          State: $sslstate"
  			echo -e "           City: $sslcity"
  			echo ""
  			echo -e "   Organization: $sslorganization"
  			echo -e "       Org Unit: $sslorgunit"
  			echo ""
  			echo -e "           FQDN: $fqdnhostname"
  			echo -e "          Email: $sslemail"
  			echo -e "           DNS1: $dnsname1"
  			echo -e "           DNS2: $dnsname2"
  			echo "---------------------------------------------------------"
  			echo ""
  			echo "Note: If any of those are blank, $sslbin will fail."
  			echo ""
  			read -r -p "Use values listed above? [Y/n] " response
				if [[ $response =~ ^(N|n|No|no|NO)$ ]]
					then
# Let User change values
  						clear
  						sleep 0.1s
						read -e -i "$sslcountry" -p "Enter two-letter Country Code: " input
    							sslcountry="${input:-$sslcountry}"
						read -e -i "$sslstate" -p "Enter State/Province Name: " input
    							sslstate="${input:-$sslstate}"
						read -e -i "$sslcity" -p "Enter City Name: " input
    							sslcity="${input:-$sslcity}"
    							echo ""
						read -e -i "$sslorganization" -p "Enter Organization Name: " input
    							sslorganization="${input:-$sslorganization}"
						read -e -i "$sslorgunit" -p "Enter Organization Unit Name: " input
    							sslorgunit="${input:-$sslorgunit}"
    							echo ""
						read -e -i "$fqdnhostname" -p "Enter FQDN Hostname: " input
    							fqdnhostname="${input:-$fqdnhostname}"
						read -e -i "$sslemail" -p "Enter Email Address: " input
    							sslemail="${input:-$sslemail}"
						read -e -i "$dnsname1" -p "Enter DNS Name 1: " input
    							dnsname1="${input:-$dnsname1}"
						read -e -i "$dnsname2" -p "Enter DNS Name 2: " input
    							dnsname2="${input:-$dnsname2}"
				fi

	done

	clear
	sleep 0.1s
}

#
# Write SSL Config
#
function postal.writessl
{
	echo "Saving SSL Config"
	if test -f "$ssldir/ssl.cnf"
		then
			:
		else
			sudo touch "$ssldir/ssl.cnf"
	fi
# Make ssl.cnf read/write-able to current user
	sudo chmod 700 $ssldir/ssl.cnf
	sudo chown $USER:$USER $ssldir/ssl.cnf

# Write variables to config
	echo "[ req ]" 							>  $ssldir/ssl.cnf
	echo "prompt = no" 							>> $ssldir/ssl.cnf
	echo "distinguished_name = req_distinguished_name" 			>> $ssldir/ssl.cnf
	echo "#req_extensions = v3_req" 					>> $ssldir/ssl.cnf
	echo "" 								>> $ssldir/ssl.cnf
	echo "[ req_distinguished_name ]" 					>> $ssldir/ssl.cnf
	echo "C = $sslcountry" 						>> $ssldir/ssl.cnf
	echo "ST = $sslstate" 							>> $ssldir/ssl.cnf
	echo "L = $sslcity" 							>> $ssldir/ssl.cnf
	echo "O = $sslorganization" 						>> $ssldir/ssl.cnf
	echo "CN = $fqdnhostname" 						>> $ssldir/ssl.cnf
	echo "OU = $sslorgunit" 						>> $ssldir/ssl.cnf
	echo "emailAddress = $sslemail" 					>> $ssldir/ssl.cnf
	echo "" 								>> $ssldir/ssl.cnf
	echo "[ alt_names ]" 							>> $ssldir/ssl.cnf
	echo "DNS.1 = $dnsname1" 						>> $ssldir/ssl.cnf
	echo "DNS.2 = $dnsname2" 						>> $ssldir/ssl.cnf
# Give back ownership to $postaluser
	sudo chown root:root $ssldir/ssl.cnf
}


# Create postal SSL key
function postal.createssl
{
	echo "Creating SSL keys"
	sudo mkdir -p "$nginxdir/ssl"
	sudo $sslbin req -x509 -newkey rsa:4096 -passout file:"$postalpass" -keyout "$nginxdir/ssl/postal.key" -out "$nginxdir/ssl/postal.cert" -days 365 -config "$ssldir/ssl.cnf"
	sudo mv "$nginxdir/ssl/postal.key" "$nginxdir/ssl/encrypted_postal.key"
	sudo $sslbin rsa -in "$nginxdir/ssl/encrypted_postal.key" -out "$nginxdir/ssl/postal.key" -passin file:"$postalpass"
	echo "Success!"
	echo ""
}



#
# MySQL
function postal.mysqldb
{
	echo "Checking for mySQL DB $postaluser."
	result=$(sudo mysql -u root -s -N -e "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME='$postaluser'");
	if [ -z "$result" ]
  		then
    			echo "$postaluser DB does not exist, creating...";
    			echo 'CREATE DATABASE `'$postaluser'` CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;' | sudo mysql -u root
  		else
    			echo "$postaluser DB already exists.";
    			echo 'SELECT table_schema '"$postaluser"', ROUND(SUM(data_length + index_length) / 1024 / 1024, 1) "DB Size in MB" FROM information_schema.tables GROUP BY table_schema;' | sudo mysql -u root -t
    			response=yes
    			read -r -p "In order to proceed, the old DB $postaluser must be deleted. Proceed? [Y/n] " response

# Ask user if they want to use existing DB, returns FALSE if yes.
    			if [[ "$response" =~ ^(Y|y|YES|yes|Yes)?$ ]]
    				then
# Double check with user.
					response=yes
					read -r -p "Are you sure you want to DELETE the DB $postaluser? [Y/n] " response
					if [[ "$response" =~ ^(Y|y|YES|yes|Yes)?$ ]]
						then
# User wants to delete the database
# Delete database
              						echo "Deleting old DB $postaluser"
              						echo 'DROP DATABASE IF EXISTS '$postaluser';' | sudo mysql -u root
# Database creation
              						echo 'CREATE DATABASE `'$postaluser'` CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci;' | sudo mysql -u root
              						echo "Database created"
              						sudo systemctl restart mysql
              						sudo systemctl restart mariadb
            					else
              						echo "Installation cannot proceed. Exiting."
              						exit 0
          				fi
      				else
        				echo "Installation cannot proceed. Exiting."
        				exit 0
			fi
	fi
}

function postal.mysqluser
{
# Check if DB user already exists
	if [ $(echo "SELECT COUNT(*) FROM mysql.user WHERE user = '$postaluser'" | sudo mysql -u root | tail -n1) -gt 0 ]
		then
  			echo "User $postaluser exists. Updating password."
    			echo 'ALTER USER '$postaluser'@'localhost' IDENTIFIED BY "'$passgen'";' | sudo mysql -u root
    			echo "Password successfully updated."
  		else
    			echo "User $postaluser doesn't exist."
    			echo "Creating mySQL user: $postaluser"
	fi

	echo 'GRANT ALL PRIVILEGES ON `'$postaluser'-%` . * to `'$postaluser'`@`localhost`  IDENTIFIED BY "'$passgen'";' | sudo mysql -u root
	echo 'FLUSH PRIVILEGES;' | sudo mysql -u root
	sudo systemctl restart mysql
        sudo systemctl restart mariadb
	echo "mySQL Configuration Completed."
# End of mySQL configuration
}


#
# RabbitMQ
function postal.rabbitmqctl
{
	echo "Checking for existing RabbitMQ config"
	sudo rabbitmqctl list_users
	response=$(sudo rabbitmqctl list_users)
	if [[ $response =~ "postal" ]]
  		then
    			echo "User $postaluser exists, continuing..."
    			echo $passgen | sudo rabbitmqctl change_password postal
  		else
    			echo "User $postaluser doesn't exist, creating..."
    			sudo rabbitmqctl add_user $postaluser $passgen
	fi
	sudo rabbitmqctl add_vhost /postal
	sudo rabbitmqctl set_permissions -p /postal $postaluser ".*" ".*" ".*"
	echo "RabbitMQ Configuration Completed."
}

#
# Application Setup
#


# Grab latest version and extract to $postaldir, check that bin is correct.
function postal.update
{
	echo "Getting latest postal application"
	sudo chown $postaluser:$postaluser -R $postaldir

	if ls "$postaldir/app" &>/dev/null
		then
			:
		else
			sudo -i -u $postaluser mkdir -p $postaldir/app
	fi
	wget https://postal.atech.media/packages/stable/latest.tgz -O - | sudo -u $postaluser tar zxpv -C $postaldir/app

	if ls "/usr/bin/postal" &>/dev/null
  		then 
  			:
  		else
      			sudo ln -s $postaldir/app/bin/postal /usr/bin/postal
	fi
}


function postal.backupconfig
{
	if ls "$postaldir/config/postal.yml" &>/dev/null
  		then
    			echo ""
    			echo "Backing up old configs"
    			sudo -i -u $postaluser cp "$postaldir/config/postal.yml" "$postaldir/config/postal_$TIMEDATE.bak"
	fi
}



function postal.generateconfig
{
	sudo -i -u $postaluser rm "$postaldir/config/postal.yml" || true
	echo ""
	echo "Initializing Postal Bundle..."
	cd "$postaldir/app"
	bundle update --bundler
	cd ~
	postal bundle $postaldir/vendor/bundle
	echo "Done"
	echo ""

	echo "Initializing Postal Config..."
	postal initialize-config
	echo "Done."
	echo ""
	echo "Modifying Postal Example Config..."
	sudo -i -u $postaluser replace "127.0.0.1" "localhost" -- $postaldir/config/postal.yml
	sudo -i -u $postaluser replace "username: postal" "username: $postaluser" -- $postaldir/config/postal.yml
	sudo -i -u $postaluser replace "password: p0stalpassw0rd" "password: $passgen" -- $postaldir/config/postal.yml
	sudo -i -u $postaluser replace "prefix: postal" "prefix: $postaluser" -- $postaldir/config/postal.yml
	sudo -i -u $postaluser replace "database: postal" "database: $postaluser" -- $postaldir/config/postal.yml
	sudo -i -u $postaluser replace "example.com" "$dnsname1" -- $postaldir/config/postal.yml
	sudo -i -u $postaluser replace "yourdomain.com" "$dnsname1" -- $postaldir/config/postal.yml
	echo "Done."
	echo ""
}

function postal.finishinstall
{
	echo "Initializing Postal..."
	postal initialize
	echo "Done."
	echo ""
	
	echo "Starting Postal"
	postal start
	echo "Done"
	echo ""
}
#
# nginx

function postal.nginx
{
	echo "Configuring nginx"
	sudo cp $postaldir/app/resource/nginx.cfg $nginxdir/sites-available/default
	sudo systemctl reload nginx
}

function postal.regenssl
{
# Use existing password or generate new one via $passgen
	postal.password
# Checks directory and user
	postal.checkdir
# Checks SSL and Regenerates certificates
	postal.readssl
	postal.modifyssl
	postal.writessl
	postal.createssl
	sudo systemctl reload nginx
}

# Installs Postal
function postal.install
{
# Grab dependecies
	postal.depend
# Use existing password or generate new one via $passgen
	postal.password
# Checks directory and user
	postal.checkdir
# Checks SSL and Regenerates certificates
	postal.readssl
	postal.modifyssl
	postal.writessl
	postal.createssl
# Checks and configures mySQL for postal
	postal.mysqldb
	postal.mysqluser
# Configures RabbitMQ
	postal.rabbitmqctl
	postal.update
	postal.backupconfig
	postal.generateconfig
	postal.finishinstall
	postal.nginx
#
# All done
#
	echo "---------------------------------------------------------"
	echo "Installation complete. Type \"postal make-user\" to create your first user."
	echo "Configuration is saved in $postaldir/config/postal.yml which you will need to edit later to use SMTP."
	echo "---------------------------------------------------------"
}

case $1 in
	("install" | "update" | "regenssl" | "showpassword")
		postal.$1
	;;
	(*)
		echo ""
		echo "Usage:"
		echo "install		- Installs postal from start to finish"
		echo "update		- Updates postal"
		echo "regenssl		- Regeneration of SSL key"
		echo "showpassword	- Displays current postal password"
		echo ""
	;;
esac


```

**Comment by willpower232** [comment]
please can you open a PR rather than using this issue? gmail has already flagged the notification of this as malicious because of all the shell script :sweat_smile:

**Comment by Lyamc** [comment]
Haha, I was not sure how to do a pull request  😆

**Comment by Lyamc** [comment]
I think I want to break some commands up into separate scripts before submitting a proper pull request, I'll leave the issue open for now so I can receive feedback. The OpenSSL part needs some tweaking for sure.

**Comment by Lyamc** [comment]
Hey, I was working on my script and I think that ruby broke `postal initialize config`

Steps to reproduce:
Install Ubuntu 20.04 LTS via:
sudo snap install lxd
lxc launch images:ubuntu/focal/amd64 focal-postal
lxc shell focal-postal
Run my script: 
[postal2.sh.txt](https://github.com/postalhq/postal/files/5687934/postal2.sh.txt)

Here's what it gets to:

```
Initializing Postal Config...
/var/lib/gems/2.7.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Traceback (most recent call last):
ruby: No such file or directory -- script/generate_initial_config.rb (LoadError)
```

When I manually run `ruby /opt/postal/script/generate_initial_config.rb` I get another error:
```
Created new private key for Let's Encrypt
Created new signing key for DKIM & HTTP requests
Traceback (most recent call last):
	4: from /opt/postal/script/generate_initial_config.rb:30:in `<main>'
	3: from /opt/postal/lib/postal/config.rb:146:in `fast_server_default_private_key_path'
	2: from /opt/postal/lib/postal/config.rb:29:in `config'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- hashie/mash (LoadError)
```

**Comment by willpower232** [comment]
Ah yes it seems there is a problem here, see https://github.com/postalhq/postal/issues/1174

**Comment by Lyamc** [comment]
Could you point me in a direction so I can try to make postal compatible with 2.7?

**Comment by willpower232** [comment]
Unfortunately I don't know enough ruby to know what is wrong here. Hopefully its a gem that needs updating rather than a breaking code change.

**Comment by Lyamc** [comment]
I've gotten a script to work inside of the lxc environment using 20.04. It's bigger than the 18.04 script because it can be run over and over without any errors.

If anyone would like to test it, be my guest!

### How to use
```
wget https://raw.githubusercontent.com/Lyamc/misc/main/ubuntu2004-postal.sh; chmod +x ubuntu2004-postal.sh
./ubuntu2004-postal.sh
```
### Using LXD Containers:
### Install LXD (if you don't have it)
```
sudo snap install lxd
sudo lxd init
```
### If you have LXD installed
```
lxc launch ubuntu:focal postal
## Forward ports to container
lxc config device add postal tcp80 proxy listen=tcp:0.0.0.0:80 connect=tcp:127.0.0.1:80
lxc config device add postal tcp443 proxy listen=tcp:0.0.0.0:443 connect=tcp:127.0.0.1:443
lxc config device add postal tcp25 proxy listen=tcp:0.0.0.0:25 connect=tcp:127.0.0.1:25
lxc config device add postal tcp2525 proxy listen=tcp:0.0.0.0:2525 connect=tcp:127.0.0.1:2525
## Allow the ports through your firewall
sudo ufw allow http
sudo ufw allow https
sudo ufw allow 25/tcp
sudo ufw allow 2525/tcp
## Show containers
lxc list
## Enter container
lxc exec postal -- su ubuntu --login
```
Now run the script.

**Comment by omueller** [comment]
It seems that downgrading to Ruby 2.6 or 2.5 (as documented under https://www.myserverfix.com/installing-ruby-on-rails-on-ubuntu-20-04-step-by-step-tutorial/ for example) could be a solution too.   I will try this on an Ubuntu 20.04 next week.

**Comment by willpower232** [comment]
RVM is certainly a way of managing your Ruby versions so should work out nicely. It could also make things easier if you aren't planning to reinstall the whole server but need to change Ruby versions.
