### ISSUE TITLE
Fast server failed

### ISSUE THREAD

**Issue by uhlhosting** [postalhq/postal#1267]
I got this all working well, untill some recents reboots, made last upgrades now it fails with:

```
|| fast
|| Quantity            1
|| Command             bundle exec rake postal:fast_server
|| Respawning          5 every 3600 seconds
|| Restart mode        term-start
|| Log path            none specified
|| Address/Port        none
|| => fast.1           Failed       02/12/2020   pid:2880     respawns:0      port:-        tag:-
```

Executing manually bundle exec rake postal:fast_server is like stuck.

postal@post:~/app$ bundle exec rake postal:fast_server --trace
** Invoke postal:fast_server (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute postal:fast_server

The log shows:

```
ESC[35m[fast.2:17030]ESC[0m [2020-12-03T22:45:06.915] INFO -- : Fast server started listening on HTTP (92.222.242.242:80)
ESC[35m[fast.2:17030]ESC[0m [2020-12-03T22:45:06.915] INFO -- : Fast server started listening on HTTPS port (92.222.242.242:443)
ESC[31m[fast.3:17159]ESC[0m [2020-12-03T22:45:26.903] INFO -- : Fast server started listening on HTTP (92.222.242.242:80)
ESC[31m[fast.3:17159]ESC[0m [2020-12-03T22:45:26.903] INFO -- : Fast server started listening on HTTPS port (92.222.242.242:443)
ESC[32m[fast.4:17279]ESC[0m [2020-12-03T22:45:37.476] INFO -- : Fast server started listening on HTTP (92.222.242.242:80)
ESC[32m[fast.4:17279]ESC[0m [2020-12-03T22:45:37.476] INFO -- : Fast server started listening on HTTPS port (92.222.242.242:443)
```

**Comment by uhlhosting** [comment]
From sentry log:

```
Interrupt: null
  from lib/postal/fast_server/server.rb:29:in `select'
  from lib/postal/fast_server/server.rb:29:in `block in run'
  from lib/postal/fast_server/server.rb:27:in `loop'
  from lib/postal/fast_server/server.rb:27:in `run'
  from lib/tasks/postal.rake:33:in `block (2 levels) in <top (required)>'
  from rake/task.rb:273:in `block in execute'
  from rake/task.rb:273:in `each'
  from rake/task.rb:273:in `execute'
  from rake/task.rb:214:in `block in invoke_with_call_chain'
  from monitor.rb:214:in `mon_synchronize'
  from rake/task.rb:194:in `invoke_with_call_chain'
  from rake/task.rb:183:in `invoke'
  from rake/application.rb:160:in `invoke_task'
  from rake/application.rb:116:in `block (2 levels) in top_level'
  from rake/application.rb:116:in `each'
  from rake/application.rb:116:in `block in top_level'
  from rake/application.rb:125:in `run_with_threads'
  from rake/application.rb:110:in `top_level'
  from rake/application.rb:83:in `block in run'
  from rake/application.rb:186:in `standard_exception_handling'
  from rake/application.rb:80:in `run'
  from /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
  from /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
  from /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```

**Comment by uhlhosting** [comment]
```
SignalException: SIGTERM
  from lib/postal/fast_server/server.rb:29:in `select'
  from lib/postal/fast_server/server.rb:29:in `block in run'
  from lib/postal/fast_server/server.rb:27:in `loop'
  from lib/postal/fast_server/server.rb:27:in `run'
  from lib/tasks/postal.rake:33:in `block (2 levels) in <top (required)>'
  from rake/task.rb:273:in `block in execute'
  from rake/task.rb:273:in `each'
  from rake/task.rb:273:in `execute'
  from rake/task.rb:214:in `block in invoke_with_call_chain'
  from monitor.rb:214:in `mon_synchronize'
  from rake/task.rb:194:in `invoke_with_call_chain'
  from rake/task.rb:183:in `invoke'
  from rake/application.rb:160:in `invoke_task'
  from rake/application.rb:116:in `block (2 levels) in top_level'
  from rake/application.rb:116:in `each'
  from rake/application.rb:116:in `block in top_level'
  from rake/application.rb:125:in `run_with_threads'
  from rake/application.rb:110:in `top_level'
  from rake/application.rb:83:in `block in run'
  from rake/application.rb:186:in `standard_exception_handling'
  from rake/application.rb:80:in `run'
  from /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
  from /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
  from /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```

**Comment by uhlhosting** [comment]
what is weird is that after few restarts it seems to be working, and when i login its failes again.

**Comment by willpower232** [comment]
Odd indeed, you could try comparing your Postal code against a fresh git checkout and see if there are any bad differences or alternatively you aren't running any antivirus or anything like that that would kill the processes randomly?
