### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by influenist** [postalhq/postal#1271]
Hi Guys,

I'm seeing this error, any idea where it goes wrong?

```
[smtp.1:24445] [2020-12-10T13:03:10.821] DEBUG -- : [F5WCFW]    Connection opened from ::ffff:****
[smtp.1:24445] [2020-12-10T13:03:10.821] DEBUG -- : [F5WCFW]    Client identified as ::ffff:****
[smtp.1:24445] [2020-12-10T13:03:10.948] DEBUG -- : [F5WCFW] <= EHLO EUR02-HE1-obe.outbound.protection.outlook.com
[smtp.1:24445] [2020-12-10T13:03:10.956] DEBUG -- : [F5WCFW] => 250-My capabilities are
[smtp.1:24445] [2020-12-10T13:03:10.956] DEBUG -- : [F5WCFW] => 250-STARTTLS
[smtp.1:24445] [2020-12-10T13:03:10.956] DEBUG -- : [F5WCFW] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:24445] [2020-12-10T13:03:11.070] DEBUG -- : [F5WCFW] <= STARTTLS
[smtp.1:24445] [2020-12-10T13:03:11.070] DEBUG -- : [F5WCFW] => 220 Ready to start TLS
[smtp.1:24445] [2020-12-10T13:03:11.226] DEBUG -- : [F5WCFW] <= EHLO EUR02-HE1-obe.outbound.protection.outlook.com
[smtp.1:24445] [2020-12-10T13:03:11.235] DEBUG -- : [F5WCFW] => 250-My capabilities are
[smtp.1:24445] [2020-12-10T13:03:11.236] DEBUG -- : [F5WCFW] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:24445] [2020-12-10T13:03:11.386] DEBUG -- : [F5WCFW] <= MAIL FROM:<p.****@****.com>
[smtp.1:24445] [2020-12-10T13:03:11.386] DEBUG -- : [F5WCFW] => 250 OK
[smtp.1:24445] [2020-12-10T13:03:11.457] DEBUG -- : [F5WCFW] <= RCPT TO:<****@****.com>
[smtp.1:24445] [2020-12-10T13:03:11.459] ERROR -- : [F5WCFW] An error occurred while processing data from a client.
[smtp.1:24445] [2020-12-10T13:03:11.459] ERROR -- : [F5WCFW] ActiveRecord::StatementInvalid: Mysql2::Error::ConnectionError: Lost connection to MySQL server during query: SELECT  `routes`.`id` AS t0_r0, `routes`.`uuid` AS t0_r1, `routes`.`server_id` AS t0_r2, `routes`.`domain_id` AS t0_r3, `routes`.`endpoint_id` AS t0_r4, `routes`.`endpoint_type` AS t0_r5, `routes`.`name` AS t0_r6, `routes`.`spam_mode` AS t0_r7, `routes`.`created_at` AS t0_r8, `routes`.`updated_at` AS t0_r9, `routes`.`token` AS t0_r10, `routes`.`mode` AS t0_r11, `domains`.`id` AS t1_r0, `domains`.`server_id` AS t1_r1, `domains`.`uuid` AS t1_r2, `domains`.`name` AS t1_r3, `domains`.`verification_token` AS t1_r4, `domains`.`verification_method` AS t1_r5, `domains`.`verified_at` AS t1_r6, `domains`.`dkim_private_key` AS t1_r7, `domains`.`created_at` AS t1_r8, `domains`.`updated_at` AS t1_r9, `domains`.`dns_checked_at` AS t1_r10, `domains`.`spf_status` AS t1_r11, `domains`.`spf_error` AS t1_r12, `domains`.`dkim_status` AS t1_r13, `domains`.`dkim_error` AS t1_r14, `domains`.`mx_status` AS t1_r15, `domains`.`mx_error` AS t1_r16, `domains`.`return_path_status` AS t1_r17, `domains`.`return_path_error` AS t1_r18, `domains`.`outgoing` AS t1_r19, `domains`.`incoming` AS t1_r20, `domains`.`owner_type` AS t1_r21, `domains`.`owner_id` AS t1_r22, `domains`.`dkim_identifier_string` AS t1_r23, `domains`.`use_for_any` AS t1_r24 FROM `routes` LEFT OUTER JOIN `domains` ON `domains`.`id` = `routes`.`domain_id` WHERE `routes`.`name` = 'info' AND `domains`.`name` = '****.com' ORDER BY `routes`.`id` ASC LIMIT 1
[smtp.1:24445] [2020-12-10T13:03:11.459] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
[smtp.1:24445] [2020-12-10T13:03:11.460] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
[smtp.1:24445] [2020-12-10T13:03:11.460] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
[smtp.1:24445] [2020-12-10T13:03:11.460] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
[smtp.1:24445] [2020-12-10T13:03:11.460] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
[smtp.1:24445] [2020-12-10T13:03:11.460] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
[smtp.1:24445] [2020-12-10T13:03:11.460] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activesupport-5.2.4.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:33:in `exec_query'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/abstract/query_cache.rb:106:in `select_all'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:555:in `block (2 levels) in exec_queries'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:398:in `apply_join_dependency'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:550:in `block in exec_queries'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:547:in `exec_queries'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:422:in `load'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:200:in `records'
[smtp.1:24445] [2020-12-10T13:03:11.461] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation.rb:195:in `to_ary'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:532:in `find_nth_with_limit'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:517:in `find_nth'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_record/relation/finder_methods.rb:125:in `first'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/app/models/route.rb:226:in `find_by_name_and_domain'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/client.rb:302:in `rcpt_to'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/client.rb:79:in `handle_command'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/client.rb:50:in `handle'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/server.rb:160:in `block (2 levels) in run_event_loop'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `select'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `block in run_event_loop'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `loop'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `run_event_loop'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/postal/smtp_server/server.rb:260:in `run'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
[smtp.1:24445] [2020-12-10T13:03:11.462] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:24445] [2020-12-10T13:03:11.463] ERROR -- : [F5WCFW] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```

**Comment by nenominal** [comment]
`[smtp.1:24445] [2020-12-10T13:03:11.459] ERROR -- : [F5WCFW] ActiveRecord::StatementInvalid: Mysql2::Error::ConnectionError: Lost connection to MySQL server during query: SELECT  `routes`.`id` AS t0_r0, `routes`.`uuid` AS t0_r1, `routes`.`server_id` AS t0_r2, `routes`.`domain_id` AS t0_r3, `routes`.`endpoint_id` AS t0_r4, `routes`.`endpoint_type` AS t0_r5, `routes`.`name` AS t0_r6, `routes`.`spam_mode` AS t0_r7, `routes`.`created_at` AS t0_r8, `routes`.`updated_at` AS t0_r9, `routes`.`token` AS t0_r10, `routes`.`mode` AS t0_r11, `domains`.`id` AS t1_r0, `domains`.`server_id` AS t1_r1, `domains`.`uuid` AS t1_r2, `domains`.`name` AS t1_r3, `domains`.`verification_token` AS t1_r4, `domains`.`verification_method` AS t1_r5, `domains`.`verified_at` AS t1_r6, `domains`.`dkim_private_key` AS t1_r7, `domains`.`created_at` AS t1_r8, `domains`.`updated_at` AS t1_r9, `domains`.`dns_checked_at` AS t1_r10, `domains`.`spf_status` AS t1_r11, `domains`.`spf_error` AS t1_r12, `domains`.`dkim_status` AS t1_r13, `domains`.`dkim_error` AS t1_r14, `domains`.`mx_status` AS t1_r15, `domains`.`mx_error` AS t1_r16, `domains`.`return_path_status` AS t1_r17, `domains`.`return_path_error` AS t1_r18, `domains`.`outgoing` AS t1_r19, `domains`.`incoming` AS t1_r20, `domains`.`owner_type` AS t1_r21, `domains`.`owner_id` AS t1_r22, `domains`.`dkim_identifier_string` AS t1_r23, `domains`.`use_for_any` AS t1_r24 FROM `routes` LEFT OUTER JOIN `domains` ON `domains`.`id` = `routes`.`domain_id` WHERE `routes`.`name` = 'info' AND `domains`.`name` = '****.com' ORDER BY `routes`.`id` ASC LIMIT 1`

It seems there's a problem with mysql server. Maybe a timeout or a network related problem if the mysql server is accessed over the network.

**Comment by willpower232** [comment]
If it isn't network related, you may need to increase some of the limits in your MySQL settings. I feel like there is an issue or two discussing this somewhere.

**Comment by influenist** [comment]
Hi @willpower232 using the default settings. Perhaps its good to have more info on the MySQL config in the readme section?

**Comment by willpower232** [comment]
That would be nice but in the meantime, the quickest reference is here https://github.com/postalhq/postal/issues/324#issuecomment-323538575
