### ISSUE TITLE
SMTP-IP Broken?

### ISSUE THREAD

**Issue by lokival** [postalhq/postal#1285]
Attempted to setup Postal Credential as follows -

Type - SMTP-IP
Name - voicedb@voice.amplia.co.tt
Network - 186.96.221.56/29
Hold - Process all messages

Need SMTP-IP as some of the hosts in the above subnet don't support SMTP authentication.

However, attempts by systems in that subnet to connect fail, see SMTP_SERVER log extract below -

----  Begin log extract ---

[smtp.1:1834] [2021-01-20T05:15:15.400] DEBUG -- : [SZJDHJ]    Connection opened from ::ffff:186.96.221.60
[smtp.1:1834] [2021-01-20T05:15:15.400] DEBUG -- : [SZJDHJ]    Client identified as ::ffff:186.96.221.60
[smtp.1:1834] [2021-01-20T05:15:15.406] DEBUG -- : [SZJDHJ] <= EHLO NexOSS1.amplia.tv
[smtp.1:1834] [2021-01-20T05:15:15.474] DEBUG -- : [SZJDHJ] => 250-My capabilities are
[smtp.1:1834] [2021-01-20T05:15:15.474] DEBUG -- : [SZJDHJ] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:1834] [2021-01-20T05:15:15.516] DEBUG -- : [SZJDHJ] <= MAIL FROM:<voicedb@voice.amplia.co.tt>
[smtp.1:1834] [2021-01-20T05:15:15.516] DEBUG -- : [SZJDHJ] => 250 OK
[smtp.1:1834] [2021-01-20T05:15:15.516] DEBUG -- : [SZJDHJ] <= RCPT TO:<gerard.valere@amplia.co.tt>
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] An error occurred while processing data from a client.
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] NoMethodError: undefined method `prefix' for #<IPAddr: IPv4:186.96.221.56/255
.255.255.248>
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/client.rb:317:in `block in rcpt_to'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_rec
ord/relation/delegation.rb:71:in `each'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/activerecord-5.2.4.3/lib/active_rec
ord/relation/delegation.rb:71:in `each'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/client.rb:317:in `sort_by'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/client.rb:317:in `rcpt_to'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/client.rb:79:in `handle_command'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/client.rb:50:in `handle'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/server.rb:160:in `block (2 levels) in
run_event_loop'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `select'
[smtp.1:1834] [2021-01-20T05:15:15.523] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `block in run_event_lo
op'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `loop'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `run_event_loop'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/app/lib/postal/smtp_server/server.rb:260:in `run'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (requir
ed)>'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
[smtp.1:1834] [2021-01-20T05:15:15.524] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
[smtp.1:1834] [2021-01-20T05:15:15.525] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
[smtp.1:1834] [2021-01-20T05:15:15.525] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
[smtp.1:1834] [2021-01-20T05:15:15.525] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
[smtp.1:1834] [2021-01-20T05:15:15.525] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
[smtp.1:1834] [2021-01-20T05:15:15.525] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:1834] [2021-01-20T05:15:15.525] ERROR -- : [SZJDHJ] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'

--- End Log Extract ---

**Comment by willpower232** [comment]
Indeed, here is a proper link to the issue https://github.com/postalhq/postal/issues/1270
