### ISSUE TITLE
Cannot send emails: FrozenError: can't modify frozen String: ""  Support Ref: J-TD9M2HP2KT

### ISSUE THREAD

**Issue by niels-smoice** [postalhq/postal#1363]
Hello,

i set up postal ona fresh Ubuntu 20.04 server.

When I try to send emails I see this message in the GUI: FrozenError: can't modify frozen String: "" 

Any idea how to solve this ?

Many thanks and best wishes

Niels

**Comment by willpower232** [comment]
Which ruby version are you using? Are you sending emails with SMTP or API?

**Comment by niels-smoice** [comment]
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux-gnu]
I am sending with SMTP. 
When I am sending from postal GUI it works.

**Comment by willpower232** [comment]
I don't think Postal supports Ubuntu 20.04 (or ruby >= 2.7) (see #1265), are you able to downgrade your ubuntu or ruby version?

**Comment by GhaziTriki** [comment]
Hello,
I am having the same issue but on Ubuntu 18.04.5 LTS with ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
I got this issue on a single mail sending only.

**Comment by adamcooke** [comment]
Can you provide a full backtrace for this error?

**Comment by radarsymphony** [comment]
Hi all, 
I also am experiencing this issue on my postal instance. Running postal in dockerized alpine 3.14.

ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]

The backtrace below seems to point to this line: https://github.com/postalserver/postal/blob/ea10ae18f10ec243c9e30a540a3de4d853155838/lib/postal/message_db/delivery.rb#L53

I have not been able to try the solution proposed here yet: https://github.com/postalserver/postal/issues/1307#issuecomment-822533242

Is this backtrace what you requested, @adamcooke? 
```
[17622] [2021-11-12T15:41:49.250] INFO -- : [XAYOOD8BLB] Started processing ESC[34mUnqueueMessageJobESC[0m job
[17622] [2021-11-12T15:41:49.253] INFO -- : [XAYOOD8BLB] Lock acquired for queued message 1111421
[17622] [2021-11-12T15:41:49.260] INFO -- : [XAYOOD8BLB] Found 0 associated messages to process at the same time (batch key: incoming-rt:-ep:-)
[17622] [2021-11-12T15:41:49.261] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] Got queued message with exclusive lock
[17622] [2021-11-12T15:41:49.261] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] Message is a bounce
[17622] [2021-11-12T15:41:49.262] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] No source messages found. Hard failing.
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] Internal error: FrozenError: can't modify frozen String: ""
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/message_db/delivery.rb:53:in `force_encoding'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/message_db/delivery.rb:53:in `webhook_hash'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/message_db/delivery.rb:44:in `send_webhooks'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/message_db/delivery.rb:11:in `create'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/message_db/message.rb:128:in `create_delivery'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/app/jobs/unqueue_message_job.rb:108:in `block in perform'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/app/jobs/unqueue_message_job.rb:30:in `each'
[17622] [2021-11-12T15:41:49.266] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/app/jobs/unqueue_message_job.rb:30:in `perform'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/worker.rb:55:in `receive_job'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /app/lib/postal/worker.rb:88:in `block in join_queue'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer.rb:56:in `call'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/channel.rb:1768:in `block in handle_frameset'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `loop'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `catch'
[17622] [2021-11-12T15:41:49.267] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] /usr/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/consumer_work_pool.rb:102:in `run_loop'
[17622] [2021-11-12T15:41:49.268] INFO -- : [XAYOOD8BLB] [1::1111287 1111421] Queued message was unlocked
[17622] [2021-11-12T15:41:49.356] INFO -- : [XAYOOD8BLB] Finished processing ESC[34mUnqueueMessageJobESC[0m job in 0.106176077s
```

**Comment by lcx** [comment]
I'm seeing this issue when server is in development mode. First I have the "held" message then the message with error. 
![CleanShot 2022-02-01 at 15 23 02](https://user-images.githubusercontent.com/891345/151985921-100d343c-6d3c-41d8-9ed7-857ef22785e9.png)

If I set the server into production mode and redeliver the message it works.

**Comment by olegbliaher** [comment]
@radarsymphony I had the same issue exactly when using Postal with rspamd, whenever an email gets marked as spam.

Modifying the line in question to this seems to solve it:

`:output => self.output.to_s+"".force_encoding('UTF-8').scrub,`

**Comment by lcx** [comment]
what I forgot, this creates an infinite loop and no messages to that email will ever work if I'm not mistaken. So you need to unqueue all messages (or delete the entries from the database) and remove that email from the suppression list. This will untangle the guardian knot. 

I would say the issue occurs here: https://github.com/postalserver/postal/blob/main/app/jobs/unqueue_message_job.rb#L68

where it creates a new delivery but without an output. and later on we run into the frozen string issue: 

https://github.com/postalserver/postal/blob/main/lib/postal/message_db/delivery.rb#L53

will try to reproduce this somehow and see if I can come up with a fix.

**Comment by udamaster** [comment]
I'm on Ubuntu 18 and 2.1.4 docker image. Seeing similar problem but not for all emails. Anyone ever figure this out? Thanks!

FrozenError: can't modify frozen String: "end of file reached"
Support Ref: J-V5RKIF8YNF

end of file reached
Time: 0.37s
Support Ref: KC5XGCGC

**Comment by olegbliaher** [comment]
@udamaster Look at my previous comment here

You need to add `to_s+""` to the line

so the whole line in its latest version looks like something like this:

`output: output.to_s+"".force_encoding("UTF-8").scrub.truncate(512),`

**Comment by anebi** [comment]
Hello, I experience the same problem. Do you edit the file directly in the Docker containers?

**Comment by anebi** [comment]
I copied the file from inside the container, patched it and modified the compose files to mount it inside the containers. I can see my patched file there but I still get the error above. The patch is not working for me unfortunately.

**Comment by hugoperes** [comment]
**I FOUND THE SOLUTION**

Simply delete the current credential (used in submission) and create a new one.

**Comment by ashishtiwari1993** [comment]
@hugoperes current credential as in smtp or api creds ?

**Comment by hugoperes** [comment]
@ashishtiwari1993 smtp

**Comment by gabrielgaliaso** [comment]
Hello, my postal version is 2.1.4 and my Rails version is 6.1.7.3 and the credentials as SMTP.

When i sent e-mail to @gmail.com all emais is mark as error like this error detail: FrozenError: can't modify frozen String: ""

To see the error on console: [https://freeimage.host/i/HiI7BMG](url)

I try create new credential but not working.

**Comment by grrinch** [comment]
Same exact issue here as @gabrielgaliaso

**Comment by Gerlowski** [comment]
Same here

**Comment by AleksY1991** [comment]
Same here

**Comment by nicksellen** [comment]
https://github.com/postalserver/postal/issues/2153 is a more recent issue for the same problem, see my comment there for a temporary fix https://github.com/postalserver/postal/issues/2153#issuecomment-1725237569
