### ISSUE TITLE
Unable to send message with attachments

### ISSUE THREAD

**Issue by igerzog** [postalhq/postal#337]
While sending message with attachments (total size is near 4202820 bytes) I get these errors:
```
[34m[smtp.1:695][0m [2017-08-30T18:42:09.586] DEBUG -- : [G8F6BM] [32m<= RCPT TO:<***@***.***>[0m
[34m[smtp.1:695][0m [2017-08-30T18:42:09.587] DEBUG -- : [G8F6BM] Added external address '***@***.***'
[34m[smtp.1:695][0m [2017-08-30T18:42:09.587] DEBUG -- : [G8F6BM] [34m=> 250 OK[0m
[34m[smtp.1:695][0m [2017-08-30T18:42:09.590] DEBUG -- : [G8F6BM] [32m<= DATA[0m
[34m[smtp.1:695][0m [2017-08-30T18:42:09.590] DEBUG -- : [G8F6BM] [34m=> 354 Go ahead[0m
[34m[smtp.1:695][0m [2017-08-30T18:42:09.594] DEBUG -- : [G8F6BM] [32m<= DomainKey-Signature: a=rsa-sha1;[0m
[34m[smtp.1:695][0m [2017-08-30T18:42:09.594] DEBUG -- : [G8F6BM] Not logging further message data.
[34m[smtp.1:695][0m [2017-08-30T18:42:17.813] ERROR -- : [G8F6BM] An error occurred while processing data from a client.
[34m[smtp.1:695][0m [2017-08-30T18:42:17.813] ERROR -- : [G8F6BM] Mysql2::Error: MySQL server has gone away
[34m[smtp.1:695][0m [2017-08-30T18:42:17.813] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.813] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.813] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.813] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.814] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.814] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/database.rb:224:in `block in insert'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.814] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.814] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/database.rb:223:in `insert'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/database.rb:115:in `insert_raw_message'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/message.rb:274:in `save_raw_message'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/message_db/message.rb:205:in `save'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/client.rb:403:in `block in finished'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/client.rb:389:in `each'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/client.rb:389:in `finished'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/client.rb:337:in `block in data'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.815] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/client.rb:47:in `handle'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.816] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/server.rb:159:in `block (2 levels) in run_event_loop'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.816] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `select'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.816] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/server.rb:86:in `block in run_event_loop'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.816] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `loop'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.816] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/server.rb:84:in `run_event_loop'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/app/lib/postal/smtp_server/server.rb:259:in `run'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.817] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.818] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.818] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.818] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.818] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.818] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[34m[smtp.1:695][0m [2017-08-30T18:42:17.819] ERROR -- : [G8F6BM] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```
The size of message does not exceed 14 MB.

**Comment by willpower232** [comment]
The error is in the first few lines `MySQL server has gone away`

You should review your memory usage, it may be that your server has insufficient memory or some other memory setting is insufficient.

**Comment by igerzog** [comment]
I have transferred postal to more powerful server. And have the same errors.

**Comment by willpower232** [comment]
Are you able to have a look at the OS logs (/var/log) to find any other indications of what has occurred?

**Comment by igerzog** [comment]
I have found the problem in mysql log file:
```
Aborted connection 13 to db: 'unconnected' user: 'postal' host: 'localhost' (Got a packet bigger than 'max_allowed_packet' bytes)
```
Have increased this variable from 4 to 32 MB at the moment. Works fine!

**Comment by willpower232** [comment]
good to know, probably worth being added to https://github.com/atech/postal/wiki/Installation

**Comment by nisanth074** [comment]
Leaving this comment in case its useful for other Postal users.

The `max_allowed_packet` configuration param can be changed in the `[mysqld]` section in `/etc/mysql/my.cnf`. I changes ours from `16MB` to `64MB`.

```
vim /etc/mysql/my.cnf
```
```
[mysqld]
# ...
max_allowed_packet      = 64M
```
```
systemctl restart mysql
```
```
root@Ubuntu-1804-bionic-64-minimal ~ # mysql
...
MariaDB [(none)]> SHOW VARIABLES LIKE 'max_allowed_packet';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| max_allowed_packet | 67108864 |
+--------------------+----------+
1 row in set (0.00 sec)
```
