### ISSUE TITLE
Email subject should support 4-byte utf8 characters

### ISSUE THREAD

**Issue by phelset** [postalhq/postal#390]
Hi
Email subject with 4-byte UTF8 characters fails on insert; Mysql2::Error exception is thrown and connection is dropped. For example subject containing emojis like: `🙈😂😱🍰`.
Even though the main database is configured with utf8mb4, the message databases isn't.

```
[smtp.1:146880] [2017-10-26T12:36:06.969] DEBUG -- : [O1XKOF]    Connection opened from ::ffff:XX.XX.XX.XX
[smtp.1:146880] [2017-10-26T12:36:06.971] DEBUG -- : [O1XKOF]    Client identified as ::ffff:XX.XX.XX.XX
[smtp.1:146880] [2017-10-26T12:36:06.973] DEBUG -- : [O1XKOF] <= EHLO XX
[smtp.1:146880] [2017-10-26T12:36:06.975] DEBUG -- : [O1XKOF] => 250-My capabilities are
[smtp.1:146880] [2017-10-26T12:36:06.975] DEBUG -- : [O1XKOF] => 250-STARTTLS
[smtp.1:146880] [2017-10-26T12:36:06.976] DEBUG -- : [O1XKOF] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:146880] [2017-10-26T12:36:07.013] DEBUG -- : [O1XKOF] <= STARTTLS
[smtp.1:146880] [2017-10-26T12:36:07.015] DEBUG -- : [O1XKOF] => 220 Ready to start TLS
[smtp.1:146880] [2017-10-26T12:36:07.038] DEBUG -- : [O1XKOF] <= EHLO localhost
[smtp.1:146880] [2017-10-26T12:36:07.041] DEBUG -- : [O1XKOF] => 250-My capabilities are
[smtp.1:146880] [2017-10-26T12:36:07.042] DEBUG -- : [O1XKOF] => 250 AUTH CRAM-MD5 PLAIN LOGIN
[smtp.1:146880] [2017-10-26T12:36:07.082] DEBUG -- : [O1XKOF] <= AUTH CRAM-MD5
[smtp.1:146880] [2017-10-26T12:36:07.083] DEBUG -- : [O1XKOF] => 334 PGU2MzQzYWRjZGU4ODI4NjE3NGNmQHBvc3RhbC5lZ2Nsb3VkLm5vPg==
[smtp.1:146880] [2017-10-26T12:36:07.085] DEBUG -- : [O1XKOF] <= XX
[smtp.1:146880] [2017-10-26T12:36:07.104] DEBUG -- : [O1XKOF] => 235 Granted for XX
[smtp.1:146880] [2017-10-26T12:36:07.106] DEBUG -- : [O1XKOF] <= MAIL FROM:<someone@example.com>
[smtp.1:146880] [2017-10-26T12:36:07.115] DEBUG -- : [O1XKOF] => 250 OK
[smtp.1:146880] [2017-10-26T12:36:07.117] DEBUG -- : [O1XKOF] <= RCPT TO:<someoneelse@example.com>
[smtp.1:146880] [2017-10-26T12:36:07.117] DEBUG -- : [O1XKOF] Added external address 'someoneelse@example.com'
[smtp.1:146880] [2017-10-26T12:36:07.118] DEBUG -- : [O1XKOF] => 250 OK
[smtp.1:146880] [2017-10-26T12:36:07.119] DEBUG -- : [O1XKOF] <= DATA
[smtp.1:146880] [2017-10-26T12:36:07.119] DEBUG -- : [O1XKOF] => 354 Go ahead
[smtp.1:146880] [2017-10-26T12:36:07.120] DEBUG -- : [O1XKOF] <= Content-Disposition: inline
[smtp.1:146880] [2017-10-26T12:36:07.121] DEBUG -- : [O1XKOF] Not logging further message data.
[smtp.1:146880] [2017-10-26T12:36:07.176] ERROR -- : [O1XKOF] An error occurred while processing data from a client.
[smtp.1:146880] [2017-10-26T12:36:07.177] ERROR -- : [O1XKOF] Mysql2::Error: Incorrect string value: '\xF0\x9D\x8C\x86'' for column 'subject' at row 1
[smtp.1:146880] [2017-10-26T12:36:07.179] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `_query'
[smtp.1:146880] [2017-10-26T12:36:07.179] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:107:in `block in query'
[smtp.1:146880] [2017-10-26T12:36:07.180] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `handle_interrupt'
[smtp.1:146880] [2017-10-26T12:36:07.181] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.4/lib/mysql2/client.rb:106:in `query'
[smtp.1:146880] [2017-10-26T12:36:07.181] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
[smtp.1:146880] [2017-10-26T12:36:07.182] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/database.rb:224:in `block in insert'
[smtp.1:146880] [2017-10-26T12:36:07.182] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
[smtp.1:146880] [2017-10-26T12:36:07.185] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
[smtp.1:146880] [2017-10-26T12:36:07.186] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/database.rb:223:in `insert'
[smtp.1:146880] [2017-10-26T12:36:07.187] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/message.rb:561:in `_create'
[smtp.1:146880] [2017-10-26T12:36:07.188] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/message_db/message.rb:206:in `save'
[smtp.1:146880] [2017-10-26T12:36:07.189] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/client.rb:410:in `block in finished'
[smtp.1:146880] [2017-10-26T12:36:07.189] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/client.rb:396:in `each'
[smtp.1:146880] [2017-10-26T12:36:07.190] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/client.rb:396:in `finished'
[smtp.1:146880] [2017-10-26T12:36:07.190] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/client.rb:339:in `block in data'
[smtp.1:146880] [2017-10-26T12:36:07.191] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/client.rb:47:in `handle'
[smtp.1:146880] [2017-10-26T12:36:07.191] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/server.rb:160:in `block (2 levels) in run_event_loop'
[smtp.1:146880] [2017-10-26T12:36:07.195] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `select'
[smtp.1:146880] [2017-10-26T12:36:07.195] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/server.rb:87:in `block in run_event_loop'
[smtp.1:146880] [2017-10-26T12:36:07.196] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `loop'
[smtp.1:146880] [2017-10-26T12:36:07.197] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/server.rb:85:in `run_event_loop'
[smtp.1:146880] [2017-10-26T12:36:07.197] ERROR -- : [O1XKOF] /opt/postal/app/lib/postal/smtp_server/server.rb:260:in `run'
[smtp.1:146880] [2017-10-26T12:36:07.198] ERROR -- : [O1XKOF] /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
[smtp.1:146880] [2017-10-26T12:36:07.199] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:248:in `block in execute'
[smtp.1:146880] [2017-10-26T12:36:07.199] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `each'
[smtp.1:146880] [2017-10-26T12:36:07.200] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
[smtp.1:146880] [2017-10-26T12:36:07.200] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:187:in `block in invoke_with_call_chain'
[smtp.1:146880] [2017-10-26T12:36:07.203] ERROR -- : [O1XKOF] /usr/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
[smtp.1:146880] [2017-10-26T12:36:07.204] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
[smtp.1:146880] [2017-10-26T12:36:07.205] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
[smtp.1:146880] [2017-10-26T12:36:07.206] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
[smtp.1:146880] [2017-10-26T12:36:07.207] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
[smtp.1:146880] [2017-10-26T12:36:07.207] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `each'
[smtp.1:146880] [2017-10-26T12:36:07.208] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:108:in `block in top_level'
[smtp.1:146880] [2017-10-26T12:36:07.208] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
[smtp.1:146880] [2017-10-26T12:36:07.211] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
[smtp.1:146880] [2017-10-26T12:36:07.212] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:80:in `block in run'
[smtp.1:146880] [2017-10-26T12:36:07.213] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
[smtp.1:146880] [2017-10-26T12:36:07.214] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
[smtp.1:146880] [2017-10-26T12:36:07.215] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
[smtp.1:146880] [2017-10-26T12:36:07.216] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `load'
[smtp.1:146880] [2017-10-26T12:36:07.220] ERROR -- : [O1XKOF] /opt/postal/vendor/bundle/ruby/2.3.0/bin/rake:22:in `<main>'
```

**Comment by catphish** [comment]
Agreed, should be easy to fix this :+1:

**Comment by atakhalighi** [comment]
Unfortunately, This issue is still there and didn't solve. :(

**Comment by willpower232** [comment]
The fix for this has been in for a while https://github.com/postalhq/postal/commit/752558f0f38723e8f90e27697df084d9b2822172

You may need to verify that you have the code mentioned in the commit and if it is, you can use a database program to verify whether your databases have been converted already. The migrations may need running manually to complete the fix depending on how or if you have upgraded.
