### ISSUE TITLE
SMTP failing when starting postal using systemd

### ISSUE THREAD

**Issue by afanjul** [postalhq/postal#809]
Hi there, when I start postal using `postal start` all things seems good. All is working. 
**However** if I use `systemctl postal start`, the SMTP service is not starting fine, and the service is not working:

The netstat shows the port 25 as opened by "master"?
```root@palbin-mail:~# netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      1341/[postal] web.1
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      320/beam.smp    
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      595/mysqld      
tcp        0      0 212.129.14.126:80       0.0.0.0:*               LISTEN      1343/[postal] fast.
tcp        0      0 163.172.203.204:80      0.0.0.0:*               LISTEN      597/nginx -g daemon
tcp        0      0 62.210.147.102:80       0.0.0.0:*               LISTEN      597/nginx -g daemon
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      418/epmd        
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      420/sshd        
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1320/master     
tcp        0      0 212.129.14.126:443      0.0.0.0:*               LISTEN      1343/[postal] fast.
tcp        0      0 163.172.203.204:443     0.0.0.0:*               LISTEN      597/nginx -g daemon
tcp        0      0 62.210.147.102:443      0.0.0.0:*               LISTEN      597/nginx -g daemon
tcp6       0      0 :::5672                 :::*                    LISTEN      320/beam.smp    
tcp6       0      0 :::4369                 :::*                    LISTEN      418/epmd        
tcp6       0      0 :::22                   :::*                    LISTEN      420/sshd        
tcp6       0      0 ::1:25                  :::*                    LISTEN      1320/master
```

And the "postal status" shows this:

```
|| smtp
|| Quantity            1
|| Command             bundle exec rake postal:smtp_server
|| Respawning          5 every 3600 seconds
|| Restart mode        usr1
|| Log path            none specified
|| Address/Port        none
|| => smtp.1           Failed       10:40        pid:1469     respawns:0      port:-        tag:-
```

And the "systemctl status postal" shows this:

```root@palbin-mail:~# systemctl status postal
postal.service - Postal Mail Platform
   Loaded: loaded (/etc/systemd/system/postal.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2019-05-08 10:40:38 UTC; 4h 47min ago
  Process: 1198 ExecStart=/usr/bin/postal start (code=exited, status=0/SUCCESS)
 Main PID: 1335 (procodile)
   CGroup: /system.slice/postal.service
           |-1335 [procodile] Postal (/opt/postal/app)           
           |-1341 [postal] web.1                                                         
           |-1343 [postal] fast.1                                                         
           |-1345 [postal] worker.1 (i 
           |-1349 [postal] worker.2 (i 
           |-1352 [postal] worker.3 (i 
           |-1355 [postal] worker.4 (i 
           |-1357 [postal] cron.1                                                  
           -1364 [postal] requeuer.1                                                  

May 08 10:40:36 palbin-mail systemd[1]: Starting Postal Mail Platform...
May 08 10:40:38 palbin-mail postal[1198]: Started Procodile supervisor with PID 1335
May 08 10:40:38 palbin-mail systemd[1]: Started Postal Mail Platform.
```

I think is due to some kind of issues with user permission or anything like that, but I don't figure out how to debug or fix it...

**Comment by willpower232** [comment]
I presume you're using the service file from the wiki?

Are you able to see if there are any entries in the `smtp_server` log file?

**Comment by afanjul** [comment]
> I presume you're using the service file from the wiki?

Yes, right that file.

Ok, it seems it only have issues when booting up for the first time, once the server is booted, doing a `systemctl restart postal` the smtp service appears...

I'm using postal inside a LXC container in Proxmox, could it be a 'symptom' but the strange thing is that ALL of the others services/packages is working fine...even the nginx front-end, 4 workers, etc.

**Comment by willpower232** [comment]
There may be another log file at `/tmp/postal/procodile.log` which should also contain some information.

**Comment by afanjul** [comment]
Ok I found the error in procodile.log, It only happens when using systemd, if I use rc.local to bootup the postal, it works fine. If I use systemd, the port 25 is opened by a mysterious process called "master".

```
14:58:12 system             | Procodile supervisor started with PID 935
14:58:12 system             | Application root is /opt/postal/app
14:58:12 control            | Listening at /tmp/postal/pids/procodile.sock
14:58:12 system             | Reloading configuration
14:58:12 web.1              | Started with PID 941
14:58:12 fast.1             | Started with PID 943
14:58:13 worker.1           | Started with PID 945
14:58:13 worker.2           | Started with PID 952
14:58:13 worker.3           | Started with PID 954
14:58:13 worker.4           | Started with PID 958
14:58:13 cron.1             | Started with PID 961
14:58:13 smtp.1             | Started with PID 964
14:58:13 requeuer.1         | Started with PID 967
14:58:14 web.1              | => Puma starting in single mode...
14:58:14 web.1              | => * Version 3.12.0 (ruby 2.3.8-p459), codename: Llamas in Pajamas
14:58:14 web.1              | => * Min threads: 5, max threads: 5
14:58:14 web.1              | => * Environment: production
14:58:20 smtp.1             | => rake aborted!
14:58:20 smtp.1             | => 
14:58:20 smtp.1             | => Errno::EADDRINUSE: Address already in use - bind(2) for "::" port 25
14:58:20 smtp.1             | => 
14:58:20 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `initialize'
14:58:20 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `open'
14:58:20 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:52:in `listen'
14:58:20 smtp.1             | => /opt/postal/app/lib/postal/smtp_server/server.rb:258:in `run'
14:58:20 smtp.1             | => /opt/postal/app/lib/tasks/postal.rake:13:in `block (2 levels) in <top (required)>'
14:58:20 smtp.1             | => /opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
14:58:20 smtp.1             | => 
14:58:20 smtp.1             | => Tasks: TOP => postal:smtp_server
14:58:20 smtp.1             | => 
14:58:20 smtp.1             | => (See full trace by running task with --trace)
14:58:20 smtp.1             | => 
14:58:20 web.1              | => * Listening on tcp://127.0.0.1:5000
14:58:20 web.1              | => Use Ctrl-C to stop
```


[Error in procodrile.log](https://i.snag.gy/3uborY.jpg)

**Comment by tchwpkgorg** [comment]
Looks like you have Postfix installed - it listens on port 25 and conflicts with Postal.
