### ISSUE TITLE
Mysql2::Error: Data too long for column 'output' at row 1

### ISSUE THREAD

**Issue by minusmillionaer** [postalhq/postal#948]
Hi,
i've restartet the virtual maschine and after boot postal, i can't send mails. Postal returns: "Mysql2::Error: Data too long for column 'output' at row 1"

> 	[worker.1:14145] [2019-12-25T14:05:43.678] INFO -- : [T4QM7KKPUW] Started processing UnqueueMessageJob job
> [worker.1:14145] [2019-12-25T14:05:43.690] INFO -- : [T4QM7KKPUW] Lock acquired for queued message 393
> [worker.1:14145] [2019-12-25T14:05:43.703] INFO -- : [T4QM7KKPUW] Found 0 associated messages to process at the same time (batch key: outgoing-netzfabrik.com)
> [worker.1:14145] [2019-12-25T14:05:43.706] INFO -- : [T4QM7KKPUW] [5::386 393] Got queued message with exclusive lock
> [worker.1:14145] [2019-12-25T14:05:43.825] INFO -- : [T4QM7KKPUW] [5::386 393] Internal error: Mysql2::Error: Data too long for column 'output' at row 1
> [worker.1:14145] [2019-12-25T14:05:43.825] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `_query'
> [worker.1:14145] [2019-12-25T14:05:43.825] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:120:in `block in query'
> [worker.1:14145] [2019-12-25T14:05:43.825] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `handle_interrupt'
> [worker.1:14145] [2019-12-25T14:05:43.825] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/mysql2-0.4.10/lib/mysql2/client.rb:119:in `query'
> [worker.1:14145] [2019-12-25T14:05:43.825] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/database.rb:224:in `block in insert'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/database.rb:223:in `insert'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/delivery.rb:8:in `create'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/message_db/message.rb:128:in `create_delivery'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/app/jobs/unqueue_message_job.rb:414:in `block in perform'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/app/jobs/unqueue_message_job.rb:30:in `each'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/app/jobs/unqueue_message_job.rb:30:in `perform'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/worker.rb:55:in `receive_job'
> [worker.1:14145] [2019-12-25T14:05:43.826] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/app/lib/postal/worker.rb:88:in `block in join_queue'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer.rb:56:in `call'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/channel.rb:1703:in `block in handle_frameset'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:97:in `block (2 levels) in run_loop'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `loop'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:92:in `block in run_loop'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `catch'
> [worker.1:14145] [2019-12-25T14:05:43.827] INFO -- : [T4QM7KKPUW] [5::386 393] /opt/postal/vendor/bundle/ruby/2.3.0/gems/bunny-2.5.1/lib/bunny/consumer_work_pool.rb:91:in `run_loop'
> [worker.1:14145] [2019-12-25T14:05:43.832] INFO -- : [T4QM7KKPUW] [5::386 393] Queued message was unlocked

<img width="571" alt="Bildschirmfoto 2019-12-25 um 14 13 41" src="https://user-images.githubusercontent.com/3305960/71446184-d093b800-2720-11ea-9c6b-924c841766b2.png">

When i want to redeliver this message, the same error occurred.

I've postal version 1.0.0-1ef7dbd67e-stable. My Database is MariaDB: "10.4.11-MariaDB"

**Comment by minusmillionaer** [comment]
I'm using a outgoing relay and in the relay was misconfigured. With `postal run` i've see more information about the error.

**Comment by udamaster** [comment]
We're seeing this as well ...what was the underlying cause of this for you?

**Comment by Gi-jutsu** [comment]
Hello, same issue here, all I can find from now are the following logs:

```
# From my postal-worker-node
# rails.log

INSERT INTO `postal-server-1`.`deliveries` (`details`, `output`, `log_id`, `status`, `message_id`, `timestamp`) VALUES ('An internal error occurred while sending this message. This message will be retried automatically. If this persists, contact support for assistance.', 'Mysql2::Error: Data too long for column \'output\' at row 1', 'J-KDVQLLQUUS', 'Error', '5', '1706546706.4095209')
```

```
# From my postal-worker-node
# worker.log

[9] [2024-01-29T16:47:47.024] INFO -- : [AUHXLE3J0W] [2::1 7] Internal error: Mysql2::Error: Data too long for column 'output' at row 1
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `_query'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:151:in `block in query'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `handle_interrupt'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/mysql2-0.5.5/lib/mysql2/client.rb:150:in `query'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/database.rb:319:in `query_on_connection'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/database.rb:223:in `block in insert'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/mysql.rb:20:in `client'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/database.rb:342:in `with_mysql'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/database.rb:222:in `insert'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/delivery.rb:8:in `create'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/message_db/message.rb:124:in `create_delivery'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/app/jobs/unqueue_message_job.rb:413:in `block in perform'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/app/jobs/unqueue_message_job.rb:31:in `each'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/app/jobs/unqueue_message_job.rb:31:in `perform'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/worker.rb:64:in `receive_job'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /opt/postal/app/lib/postal/worker.rb:96:in `block in join_queue'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer.rb:56:in `call'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/channel.rb:1842:in `block in handle_frameset'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:108:in `block (2 levels) in run_loop'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in `loop'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:103:in `block in run_loop'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in `catch'
[9] [2024-01-29T16:47:47.025] INFO -- : [AUHXLE3J0W] [2::1 7] /usr/local/bundle/gems/bunny-2.20.3/lib/bunny/consumer_work_pool.rb:102:in `run_loop'
[9] [2024-01-29T16:47:47.045] INFO -- : [AUHXLE3J0W] [2::1 7] Queued message was unlocked
```

I'll be looking further if I can find the cause of the issue
