### ISSUE TITLE
Upgrade Error - Autoprefixer doesn’t support Node v4.2.6 (after Compiling Assets)

### ISSUE THREAD

**Issue by iammattmartin** [postalhq/postal#971]
Had a pretty nasty error on trying to upgrade.

```
Compiling Assets
rake aborted!
Autoprefixer doesn’t support Node v4.2.6. Update it.
/opt/postal/vendor/bundle/ruby/2.3.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/processor.rb:163:in `runtime'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/processor.rb:37:in `process'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/sprockets.rb:20:in `run'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/autoprefixer-rails-9.1.3/lib/autoprefixer-rails/sprockets.rb:14:in `call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:142:in `block in find'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:231:in `block in stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:140:in `find'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
/opt/postal/vendor/bundle/ruby/2.3.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => assets:precompile
(See full trace by running task with --trace)
Failed to run: postal upgrade
```

There isn't much there which I can see is useful (apart from the autoprefixer message), although, those with more Ruby experience may be able to see something obvious.

Already have the latest nodejs installed
`nodejs is already the newest version (4.2.6~dfsg-1ubuntu4.2).`

**Comment by iammattmartin** [comment]
Although I couldn't see it in the docs, I removed the default version that comes with ubuntu and installed the latest.

```
apt remove nodejs
curl -sL https://deb.nodesource.com/setup_10.x | bash -
sudo apt-get install -y nodejs
```

Upgraded and started OK. Would be good to hear if this may cause any issues however as the version jump is huge (4.x to 10.x).

**Comment by willpower232** [comment]
Thanks for letting us know, this sounds like a really-old-ubuntu problem and nodesource is definitely the answer.

[autoprefixer-rails](https://github.com/ai/autoprefixer-rails) claims support for node >= 6 and isn't more specific so you should be fine but version 12 is also available so that might be a slightly longer term option.

**Comment by iammattmartin** [comment]
Yeah, our install was probably one of the first so has been "as-is" for a long time. Probably a gotcha that will catch a few out in similar circumstances.
